// Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License"). You may
// not use this file except in compliance with the License. A copy of the
// License is located at
//
//     http://aws.amazon.com/apache2.0/
//
// or in the "license" file accompanying this file. This file is distributed
// on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
// express or implied. See the License for the specific language governing
// permissions and limitations under the License.

// Code generated by ack-generate. DO NOT EDIT.

package environment

import (
	"bytes"

	ackcompare "github.com/aws-controllers-k8s/runtime/pkg/compare"
	acktags "github.com/aws-controllers-k8s/runtime/pkg/tags"
)

// Hack to avoid import errors during build...
var (
	_ = &bytes.Buffer{}
	_ = &acktags.Tags{}
)

// newResourceDelta returns a new `ackcompare.Delta` used to compare two
// resources
func newResourceDelta(
	a *resource,
	b *resource,
) *ackcompare.Delta {
	delta := ackcompare.NewDelta()
	if (a == nil && b != nil) ||
		(a != nil && b == nil) {
		delta.Add("", a, b)
		return delta
	}

	if len(a.ko.Spec.AirflowConfigurationOptions) != len(b.ko.Spec.AirflowConfigurationOptions) {
		delta.Add("Spec.AirflowConfigurationOptions", a.ko.Spec.AirflowConfigurationOptions, b.ko.Spec.AirflowConfigurationOptions)
	} else if len(a.ko.Spec.AirflowConfigurationOptions) > 0 {
		if !ackcompare.MapStringStringPEqual(a.ko.Spec.AirflowConfigurationOptions, b.ko.Spec.AirflowConfigurationOptions) {
			delta.Add("Spec.AirflowConfigurationOptions", a.ko.Spec.AirflowConfigurationOptions, b.ko.Spec.AirflowConfigurationOptions)
		}
	}
	if ackcompare.HasNilDifference(a.ko.Spec.AirflowVersion, b.ko.Spec.AirflowVersion) {
		delta.Add("Spec.AirflowVersion", a.ko.Spec.AirflowVersion, b.ko.Spec.AirflowVersion)
	} else if a.ko.Spec.AirflowVersion != nil && b.ko.Spec.AirflowVersion != nil {
		if *a.ko.Spec.AirflowVersion != *b.ko.Spec.AirflowVersion {
			delta.Add("Spec.AirflowVersion", a.ko.Spec.AirflowVersion, b.ko.Spec.AirflowVersion)
		}
	}
	if ackcompare.HasNilDifference(a.ko.Spec.DagS3Path, b.ko.Spec.DagS3Path) {
		delta.Add("Spec.DagS3Path", a.ko.Spec.DagS3Path, b.ko.Spec.DagS3Path)
	} else if a.ko.Spec.DagS3Path != nil && b.ko.Spec.DagS3Path != nil {
		if *a.ko.Spec.DagS3Path != *b.ko.Spec.DagS3Path {
			delta.Add("Spec.DagS3Path", a.ko.Spec.DagS3Path, b.ko.Spec.DagS3Path)
		}
	}
	if ackcompare.HasNilDifference(a.ko.Spec.EndpointManagement, b.ko.Spec.EndpointManagement) {
		delta.Add("Spec.EndpointManagement", a.ko.Spec.EndpointManagement, b.ko.Spec.EndpointManagement)
	} else if a.ko.Spec.EndpointManagement != nil && b.ko.Spec.EndpointManagement != nil {
		if *a.ko.Spec.EndpointManagement != *b.ko.Spec.EndpointManagement {
			delta.Add("Spec.EndpointManagement", a.ko.Spec.EndpointManagement, b.ko.Spec.EndpointManagement)
		}
	}
	if ackcompare.HasNilDifference(a.ko.Spec.EnvironmentClass, b.ko.Spec.EnvironmentClass) {
		delta.Add("Spec.EnvironmentClass", a.ko.Spec.EnvironmentClass, b.ko.Spec.EnvironmentClass)
	} else if a.ko.Spec.EnvironmentClass != nil && b.ko.Spec.EnvironmentClass != nil {
		if *a.ko.Spec.EnvironmentClass != *b.ko.Spec.EnvironmentClass {
			delta.Add("Spec.EnvironmentClass", a.ko.Spec.EnvironmentClass, b.ko.Spec.EnvironmentClass)
		}
	}
	if ackcompare.HasNilDifference(a.ko.Spec.ExecutionRoleARN, b.ko.Spec.ExecutionRoleARN) {
		delta.Add("Spec.ExecutionRoleARN", a.ko.Spec.ExecutionRoleARN, b.ko.Spec.ExecutionRoleARN)
	} else if a.ko.Spec.ExecutionRoleARN != nil && b.ko.Spec.ExecutionRoleARN != nil {
		if *a.ko.Spec.ExecutionRoleARN != *b.ko.Spec.ExecutionRoleARN {
			delta.Add("Spec.ExecutionRoleARN", a.ko.Spec.ExecutionRoleARN, b.ko.Spec.ExecutionRoleARN)
		}
	}
	if ackcompare.HasNilDifference(a.ko.Spec.KMSKey, b.ko.Spec.KMSKey) {
		delta.Add("Spec.KMSKey", a.ko.Spec.KMSKey, b.ko.Spec.KMSKey)
	} else if a.ko.Spec.KMSKey != nil && b.ko.Spec.KMSKey != nil {
		if *a.ko.Spec.KMSKey != *b.ko.Spec.KMSKey {
			delta.Add("Spec.KMSKey", a.ko.Spec.KMSKey, b.ko.Spec.KMSKey)
		}
	}
	if ackcompare.HasNilDifference(a.ko.Spec.LoggingConfiguration, b.ko.Spec.LoggingConfiguration) {
		delta.Add("Spec.LoggingConfiguration", a.ko.Spec.LoggingConfiguration, b.ko.Spec.LoggingConfiguration)
	} else if a.ko.Spec.LoggingConfiguration != nil && b.ko.Spec.LoggingConfiguration != nil {
		if ackcompare.HasNilDifference(a.ko.Spec.LoggingConfiguration.DagProcessingLogs, b.ko.Spec.LoggingConfiguration.DagProcessingLogs) {
			delta.Add("Spec.LoggingConfiguration.DagProcessingLogs", a.ko.Spec.LoggingConfiguration.DagProcessingLogs, b.ko.Spec.LoggingConfiguration.DagProcessingLogs)
		} else if a.ko.Spec.LoggingConfiguration.DagProcessingLogs != nil && b.ko.Spec.LoggingConfiguration.DagProcessingLogs != nil {
			if ackcompare.HasNilDifference(a.ko.Spec.LoggingConfiguration.DagProcessingLogs.Enabled, b.ko.Spec.LoggingConfiguration.DagProcessingLogs.Enabled) {
				delta.Add("Spec.LoggingConfiguration.DagProcessingLogs.Enabled", a.ko.Spec.LoggingConfiguration.DagProcessingLogs.Enabled, b.ko.Spec.LoggingConfiguration.DagProcessingLogs.Enabled)
			} else if a.ko.Spec.LoggingConfiguration.DagProcessingLogs.Enabled != nil && b.ko.Spec.LoggingConfiguration.DagProcessingLogs.Enabled != nil {
				if *a.ko.Spec.LoggingConfiguration.DagProcessingLogs.Enabled != *b.ko.Spec.LoggingConfiguration.DagProcessingLogs.Enabled {
					delta.Add("Spec.LoggingConfiguration.DagProcessingLogs.Enabled", a.ko.Spec.LoggingConfiguration.DagProcessingLogs.Enabled, b.ko.Spec.LoggingConfiguration.DagProcessingLogs.Enabled)
				}
			}
			if ackcompare.HasNilDifference(a.ko.Spec.LoggingConfiguration.DagProcessingLogs.LogLevel, b.ko.Spec.LoggingConfiguration.DagProcessingLogs.LogLevel) {
				delta.Add("Spec.LoggingConfiguration.DagProcessingLogs.LogLevel", a.ko.Spec.LoggingConfiguration.DagProcessingLogs.LogLevel, b.ko.Spec.LoggingConfiguration.DagProcessingLogs.LogLevel)
			} else if a.ko.Spec.LoggingConfiguration.DagProcessingLogs.LogLevel != nil && b.ko.Spec.LoggingConfiguration.DagProcessingLogs.LogLevel != nil {
				if *a.ko.Spec.LoggingConfiguration.DagProcessingLogs.LogLevel != *b.ko.Spec.LoggingConfiguration.DagProcessingLogs.LogLevel {
					delta.Add("Spec.LoggingConfiguration.DagProcessingLogs.LogLevel", a.ko.Spec.LoggingConfiguration.DagProcessingLogs.LogLevel, b.ko.Spec.LoggingConfiguration.DagProcessingLogs.LogLevel)
				}
			}
		}
		if ackcompare.HasNilDifference(a.ko.Spec.LoggingConfiguration.SchedulerLogs, b.ko.Spec.LoggingConfiguration.SchedulerLogs) {
			delta.Add("Spec.LoggingConfiguration.SchedulerLogs", a.ko.Spec.LoggingConfiguration.SchedulerLogs, b.ko.Spec.LoggingConfiguration.SchedulerLogs)
		} else if a.ko.Spec.LoggingConfiguration.SchedulerLogs != nil && b.ko.Spec.LoggingConfiguration.SchedulerLogs != nil {
			if ackcompare.HasNilDifference(a.ko.Spec.LoggingConfiguration.SchedulerLogs.Enabled, b.ko.Spec.LoggingConfiguration.SchedulerLogs.Enabled) {
				delta.Add("Spec.LoggingConfiguration.SchedulerLogs.Enabled", a.ko.Spec.LoggingConfiguration.SchedulerLogs.Enabled, b.ko.Spec.LoggingConfiguration.SchedulerLogs.Enabled)
			} else if a.ko.Spec.LoggingConfiguration.SchedulerLogs.Enabled != nil && b.ko.Spec.LoggingConfiguration.SchedulerLogs.Enabled != nil {
				if *a.ko.Spec.LoggingConfiguration.SchedulerLogs.Enabled != *b.ko.Spec.LoggingConfiguration.SchedulerLogs.Enabled {
					delta.Add("Spec.LoggingConfiguration.SchedulerLogs.Enabled", a.ko.Spec.LoggingConfiguration.SchedulerLogs.Enabled, b.ko.Spec.LoggingConfiguration.SchedulerLogs.Enabled)
				}
			}
			if ackcompare.HasNilDifference(a.ko.Spec.LoggingConfiguration.SchedulerLogs.LogLevel, b.ko.Spec.LoggingConfiguration.SchedulerLogs.LogLevel) {
				delta.Add("Spec.LoggingConfiguration.SchedulerLogs.LogLevel", a.ko.Spec.LoggingConfiguration.SchedulerLogs.LogLevel, b.ko.Spec.LoggingConfiguration.SchedulerLogs.LogLevel)
			} else if a.ko.Spec.LoggingConfiguration.SchedulerLogs.LogLevel != nil && b.ko.Spec.LoggingConfiguration.SchedulerLogs.LogLevel != nil {
				if *a.ko.Spec.LoggingConfiguration.SchedulerLogs.LogLevel != *b.ko.Spec.LoggingConfiguration.SchedulerLogs.LogLevel {
					delta.Add("Spec.LoggingConfiguration.SchedulerLogs.LogLevel", a.ko.Spec.LoggingConfiguration.SchedulerLogs.LogLevel, b.ko.Spec.LoggingConfiguration.SchedulerLogs.LogLevel)
				}
			}
		}
		if ackcompare.HasNilDifference(a.ko.Spec.LoggingConfiguration.TaskLogs, b.ko.Spec.LoggingConfiguration.TaskLogs) {
			delta.Add("Spec.LoggingConfiguration.TaskLogs", a.ko.Spec.LoggingConfiguration.TaskLogs, b.ko.Spec.LoggingConfiguration.TaskLogs)
		} else if a.ko.Spec.LoggingConfiguration.TaskLogs != nil && b.ko.Spec.LoggingConfiguration.TaskLogs != nil {
			if ackcompare.HasNilDifference(a.ko.Spec.LoggingConfiguration.TaskLogs.Enabled, b.ko.Spec.LoggingConfiguration.TaskLogs.Enabled) {
				delta.Add("Spec.LoggingConfiguration.TaskLogs.Enabled", a.ko.Spec.LoggingConfiguration.TaskLogs.Enabled, b.ko.Spec.LoggingConfiguration.TaskLogs.Enabled)
			} else if a.ko.Spec.LoggingConfiguration.TaskLogs.Enabled != nil && b.ko.Spec.LoggingConfiguration.TaskLogs.Enabled != nil {
				if *a.ko.Spec.LoggingConfiguration.TaskLogs.Enabled != *b.ko.Spec.LoggingConfiguration.TaskLogs.Enabled {
					delta.Add("Spec.LoggingConfiguration.TaskLogs.Enabled", a.ko.Spec.LoggingConfiguration.TaskLogs.Enabled, b.ko.Spec.LoggingConfiguration.TaskLogs.Enabled)
				}
			}
			if ackcompare.HasNilDifference(a.ko.Spec.LoggingConfiguration.TaskLogs.LogLevel, b.ko.Spec.LoggingConfiguration.TaskLogs.LogLevel) {
				delta.Add("Spec.LoggingConfiguration.TaskLogs.LogLevel", a.ko.Spec.LoggingConfiguration.TaskLogs.LogLevel, b.ko.Spec.LoggingConfiguration.TaskLogs.LogLevel)
			} else if a.ko.Spec.LoggingConfiguration.TaskLogs.LogLevel != nil && b.ko.Spec.LoggingConfiguration.TaskLogs.LogLevel != nil {
				if *a.ko.Spec.LoggingConfiguration.TaskLogs.LogLevel != *b.ko.Spec.LoggingConfiguration.TaskLogs.LogLevel {
					delta.Add("Spec.LoggingConfiguration.TaskLogs.LogLevel", a.ko.Spec.LoggingConfiguration.TaskLogs.LogLevel, b.ko.Spec.LoggingConfiguration.TaskLogs.LogLevel)
				}
			}
		}
		if ackcompare.HasNilDifference(a.ko.Spec.LoggingConfiguration.WebserverLogs, b.ko.Spec.LoggingConfiguration.WebserverLogs) {
			delta.Add("Spec.LoggingConfiguration.WebserverLogs", a.ko.Spec.LoggingConfiguration.WebserverLogs, b.ko.Spec.LoggingConfiguration.WebserverLogs)
		} else if a.ko.Spec.LoggingConfiguration.WebserverLogs != nil && b.ko.Spec.LoggingConfiguration.WebserverLogs != nil {
			if ackcompare.HasNilDifference(a.ko.Spec.LoggingConfiguration.WebserverLogs.Enabled, b.ko.Spec.LoggingConfiguration.WebserverLogs.Enabled) {
				delta.Add("Spec.LoggingConfiguration.WebserverLogs.Enabled", a.ko.Spec.LoggingConfiguration.WebserverLogs.Enabled, b.ko.Spec.LoggingConfiguration.WebserverLogs.Enabled)
			} else if a.ko.Spec.LoggingConfiguration.WebserverLogs.Enabled != nil && b.ko.Spec.LoggingConfiguration.WebserverLogs.Enabled != nil {
				if *a.ko.Spec.LoggingConfiguration.WebserverLogs.Enabled != *b.ko.Spec.LoggingConfiguration.WebserverLogs.Enabled {
					delta.Add("Spec.LoggingConfiguration.WebserverLogs.Enabled", a.ko.Spec.LoggingConfiguration.WebserverLogs.Enabled, b.ko.Spec.LoggingConfiguration.WebserverLogs.Enabled)
				}
			}
			if ackcompare.HasNilDifference(a.ko.Spec.LoggingConfiguration.WebserverLogs.LogLevel, b.ko.Spec.LoggingConfiguration.WebserverLogs.LogLevel) {
				delta.Add("Spec.LoggingConfiguration.WebserverLogs.LogLevel", a.ko.Spec.LoggingConfiguration.WebserverLogs.LogLevel, b.ko.Spec.LoggingConfiguration.WebserverLogs.LogLevel)
			} else if a.ko.Spec.LoggingConfiguration.WebserverLogs.LogLevel != nil && b.ko.Spec.LoggingConfiguration.WebserverLogs.LogLevel != nil {
				if *a.ko.Spec.LoggingConfiguration.WebserverLogs.LogLevel != *b.ko.Spec.LoggingConfiguration.WebserverLogs.LogLevel {
					delta.Add("Spec.LoggingConfiguration.WebserverLogs.LogLevel", a.ko.Spec.LoggingConfiguration.WebserverLogs.LogLevel, b.ko.Spec.LoggingConfiguration.WebserverLogs.LogLevel)
				}
			}
		}
		if ackcompare.HasNilDifference(a.ko.Spec.LoggingConfiguration.WorkerLogs, b.ko.Spec.LoggingConfiguration.WorkerLogs) {
			delta.Add("Spec.LoggingConfiguration.WorkerLogs", a.ko.Spec.LoggingConfiguration.WorkerLogs, b.ko.Spec.LoggingConfiguration.WorkerLogs)
		} else if a.ko.Spec.LoggingConfiguration.WorkerLogs != nil && b.ko.Spec.LoggingConfiguration.WorkerLogs != nil {
			if ackcompare.HasNilDifference(a.ko.Spec.LoggingConfiguration.WorkerLogs.Enabled, b.ko.Spec.LoggingConfiguration.WorkerLogs.Enabled) {
				delta.Add("Spec.LoggingConfiguration.WorkerLogs.Enabled", a.ko.Spec.LoggingConfiguration.WorkerLogs.Enabled, b.ko.Spec.LoggingConfiguration.WorkerLogs.Enabled)
			} else if a.ko.Spec.LoggingConfiguration.WorkerLogs.Enabled != nil && b.ko.Spec.LoggingConfiguration.WorkerLogs.Enabled != nil {
				if *a.ko.Spec.LoggingConfiguration.WorkerLogs.Enabled != *b.ko.Spec.LoggingConfiguration.WorkerLogs.Enabled {
					delta.Add("Spec.LoggingConfiguration.WorkerLogs.Enabled", a.ko.Spec.LoggingConfiguration.WorkerLogs.Enabled, b.ko.Spec.LoggingConfiguration.WorkerLogs.Enabled)
				}
			}
			if ackcompare.HasNilDifference(a.ko.Spec.LoggingConfiguration.WorkerLogs.LogLevel, b.ko.Spec.LoggingConfiguration.WorkerLogs.LogLevel) {
				delta.Add("Spec.LoggingConfiguration.WorkerLogs.LogLevel", a.ko.Spec.LoggingConfiguration.WorkerLogs.LogLevel, b.ko.Spec.LoggingConfiguration.WorkerLogs.LogLevel)
			} else if a.ko.Spec.LoggingConfiguration.WorkerLogs.LogLevel != nil && b.ko.Spec.LoggingConfiguration.WorkerLogs.LogLevel != nil {
				if *a.ko.Spec.LoggingConfiguration.WorkerLogs.LogLevel != *b.ko.Spec.LoggingConfiguration.WorkerLogs.LogLevel {
					delta.Add("Spec.LoggingConfiguration.WorkerLogs.LogLevel", a.ko.Spec.LoggingConfiguration.WorkerLogs.LogLevel, b.ko.Spec.LoggingConfiguration.WorkerLogs.LogLevel)
				}
			}
		}
	}
	if ackcompare.HasNilDifference(a.ko.Spec.MaxWebservers, b.ko.Spec.MaxWebservers) {
		delta.Add("Spec.MaxWebservers", a.ko.Spec.MaxWebservers, b.ko.Spec.MaxWebservers)
	} else if a.ko.Spec.MaxWebservers != nil && b.ko.Spec.MaxWebservers != nil {
		if *a.ko.Spec.MaxWebservers != *b.ko.Spec.MaxWebservers {
			delta.Add("Spec.MaxWebservers", a.ko.Spec.MaxWebservers, b.ko.Spec.MaxWebservers)
		}
	}
	if ackcompare.HasNilDifference(a.ko.Spec.MaxWorkers, b.ko.Spec.MaxWorkers) {
		delta.Add("Spec.MaxWorkers", a.ko.Spec.MaxWorkers, b.ko.Spec.MaxWorkers)
	} else if a.ko.Spec.MaxWorkers != nil && b.ko.Spec.MaxWorkers != nil {
		if *a.ko.Spec.MaxWorkers != *b.ko.Spec.MaxWorkers {
			delta.Add("Spec.MaxWorkers", a.ko.Spec.MaxWorkers, b.ko.Spec.MaxWorkers)
		}
	}
	if ackcompare.HasNilDifference(a.ko.Spec.MinWebservers, b.ko.Spec.MinWebservers) {
		delta.Add("Spec.MinWebservers", a.ko.Spec.MinWebservers, b.ko.Spec.MinWebservers)
	} else if a.ko.Spec.MinWebservers != nil && b.ko.Spec.MinWebservers != nil {
		if *a.ko.Spec.MinWebservers != *b.ko.Spec.MinWebservers {
			delta.Add("Spec.MinWebservers", a.ko.Spec.MinWebservers, b.ko.Spec.MinWebservers)
		}
	}
	if ackcompare.HasNilDifference(a.ko.Spec.MinWorkers, b.ko.Spec.MinWorkers) {
		delta.Add("Spec.MinWorkers", a.ko.Spec.MinWorkers, b.ko.Spec.MinWorkers)
	} else if a.ko.Spec.MinWorkers != nil && b.ko.Spec.MinWorkers != nil {
		if *a.ko.Spec.MinWorkers != *b.ko.Spec.MinWorkers {
			delta.Add("Spec.MinWorkers", a.ko.Spec.MinWorkers, b.ko.Spec.MinWorkers)
		}
	}
	if ackcompare.HasNilDifference(a.ko.Spec.Name, b.ko.Spec.Name) {
		delta.Add("Spec.Name", a.ko.Spec.Name, b.ko.Spec.Name)
	} else if a.ko.Spec.Name != nil && b.ko.Spec.Name != nil {
		if *a.ko.Spec.Name != *b.ko.Spec.Name {
			delta.Add("Spec.Name", a.ko.Spec.Name, b.ko.Spec.Name)
		}
	}
	if ackcompare.HasNilDifference(a.ko.Spec.NetworkConfiguration, b.ko.Spec.NetworkConfiguration) {
		delta.Add("Spec.NetworkConfiguration", a.ko.Spec.NetworkConfiguration, b.ko.Spec.NetworkConfiguration)
	} else if a.ko.Spec.NetworkConfiguration != nil && b.ko.Spec.NetworkConfiguration != nil {
		if len(a.ko.Spec.NetworkConfiguration.SecurityGroupIDs) != len(b.ko.Spec.NetworkConfiguration.SecurityGroupIDs) {
			delta.Add("Spec.NetworkConfiguration.SecurityGroupIDs", a.ko.Spec.NetworkConfiguration.SecurityGroupIDs, b.ko.Spec.NetworkConfiguration.SecurityGroupIDs)
		} else if len(a.ko.Spec.NetworkConfiguration.SecurityGroupIDs) > 0 {
			if !ackcompare.SliceStringPEqual(a.ko.Spec.NetworkConfiguration.SecurityGroupIDs, b.ko.Spec.NetworkConfiguration.SecurityGroupIDs) {
				delta.Add("Spec.NetworkConfiguration.SecurityGroupIDs", a.ko.Spec.NetworkConfiguration.SecurityGroupIDs, b.ko.Spec.NetworkConfiguration.SecurityGroupIDs)
			}
		}
		if len(a.ko.Spec.NetworkConfiguration.SubnetIDs) != len(b.ko.Spec.NetworkConfiguration.SubnetIDs) {
			delta.Add("Spec.NetworkConfiguration.SubnetIDs", a.ko.Spec.NetworkConfiguration.SubnetIDs, b.ko.Spec.NetworkConfiguration.SubnetIDs)
		} else if len(a.ko.Spec.NetworkConfiguration.SubnetIDs) > 0 {
			if !ackcompare.SliceStringPEqual(a.ko.Spec.NetworkConfiguration.SubnetIDs, b.ko.Spec.NetworkConfiguration.SubnetIDs) {
				delta.Add("Spec.NetworkConfiguration.SubnetIDs", a.ko.Spec.NetworkConfiguration.SubnetIDs, b.ko.Spec.NetworkConfiguration.SubnetIDs)
			}
		}
	}
	if ackcompare.HasNilDifference(a.ko.Spec.PluginsS3ObjectVersion, b.ko.Spec.PluginsS3ObjectVersion) {
		delta.Add("Spec.PluginsS3ObjectVersion", a.ko.Spec.PluginsS3ObjectVersion, b.ko.Spec.PluginsS3ObjectVersion)
	} else if a.ko.Spec.PluginsS3ObjectVersion != nil && b.ko.Spec.PluginsS3ObjectVersion != nil {
		if *a.ko.Spec.PluginsS3ObjectVersion != *b.ko.Spec.PluginsS3ObjectVersion {
			delta.Add("Spec.PluginsS3ObjectVersion", a.ko.Spec.PluginsS3ObjectVersion, b.ko.Spec.PluginsS3ObjectVersion)
		}
	}
	if ackcompare.HasNilDifference(a.ko.Spec.PluginsS3Path, b.ko.Spec.PluginsS3Path) {
		delta.Add("Spec.PluginsS3Path", a.ko.Spec.PluginsS3Path, b.ko.Spec.PluginsS3Path)
	} else if a.ko.Spec.PluginsS3Path != nil && b.ko.Spec.PluginsS3Path != nil {
		if *a.ko.Spec.PluginsS3Path != *b.ko.Spec.PluginsS3Path {
			delta.Add("Spec.PluginsS3Path", a.ko.Spec.PluginsS3Path, b.ko.Spec.PluginsS3Path)
		}
	}
	if ackcompare.HasNilDifference(a.ko.Spec.RequirementsS3ObjectVersion, b.ko.Spec.RequirementsS3ObjectVersion) {
		delta.Add("Spec.RequirementsS3ObjectVersion", a.ko.Spec.RequirementsS3ObjectVersion, b.ko.Spec.RequirementsS3ObjectVersion)
	} else if a.ko.Spec.RequirementsS3ObjectVersion != nil && b.ko.Spec.RequirementsS3ObjectVersion != nil {
		if *a.ko.Spec.RequirementsS3ObjectVersion != *b.ko.Spec.RequirementsS3ObjectVersion {
			delta.Add("Spec.RequirementsS3ObjectVersion", a.ko.Spec.RequirementsS3ObjectVersion, b.ko.Spec.RequirementsS3ObjectVersion)
		}
	}
	if ackcompare.HasNilDifference(a.ko.Spec.RequirementsS3Path, b.ko.Spec.RequirementsS3Path) {
		delta.Add("Spec.RequirementsS3Path", a.ko.Spec.RequirementsS3Path, b.ko.Spec.RequirementsS3Path)
	} else if a.ko.Spec.RequirementsS3Path != nil && b.ko.Spec.RequirementsS3Path != nil {
		if *a.ko.Spec.RequirementsS3Path != *b.ko.Spec.RequirementsS3Path {
			delta.Add("Spec.RequirementsS3Path", a.ko.Spec.RequirementsS3Path, b.ko.Spec.RequirementsS3Path)
		}
	}
	if ackcompare.HasNilDifference(a.ko.Spec.Schedulers, b.ko.Spec.Schedulers) {
		delta.Add("Spec.Schedulers", a.ko.Spec.Schedulers, b.ko.Spec.Schedulers)
	} else if a.ko.Spec.Schedulers != nil && b.ko.Spec.Schedulers != nil {
		if *a.ko.Spec.Schedulers != *b.ko.Spec.Schedulers {
			delta.Add("Spec.Schedulers", a.ko.Spec.Schedulers, b.ko.Spec.Schedulers)
		}
	}
	if ackcompare.HasNilDifference(a.ko.Spec.SourceBucketARN, b.ko.Spec.SourceBucketARN) {
		delta.Add("Spec.SourceBucketARN", a.ko.Spec.SourceBucketARN, b.ko.Spec.SourceBucketARN)
	} else if a.ko.Spec.SourceBucketARN != nil && b.ko.Spec.SourceBucketARN != nil {
		if *a.ko.Spec.SourceBucketARN != *b.ko.Spec.SourceBucketARN {
			delta.Add("Spec.SourceBucketARN", a.ko.Spec.SourceBucketARN, b.ko.Spec.SourceBucketARN)
		}
	}
	if ackcompare.HasNilDifference(a.ko.Spec.StartupScriptS3ObjectVersion, b.ko.Spec.StartupScriptS3ObjectVersion) {
		delta.Add("Spec.StartupScriptS3ObjectVersion", a.ko.Spec.StartupScriptS3ObjectVersion, b.ko.Spec.StartupScriptS3ObjectVersion)
	} else if a.ko.Spec.StartupScriptS3ObjectVersion != nil && b.ko.Spec.StartupScriptS3ObjectVersion != nil {
		if *a.ko.Spec.StartupScriptS3ObjectVersion != *b.ko.Spec.StartupScriptS3ObjectVersion {
			delta.Add("Spec.StartupScriptS3ObjectVersion", a.ko.Spec.StartupScriptS3ObjectVersion, b.ko.Spec.StartupScriptS3ObjectVersion)
		}
	}
	if ackcompare.HasNilDifference(a.ko.Spec.StartupScriptS3Path, b.ko.Spec.StartupScriptS3Path) {
		delta.Add("Spec.StartupScriptS3Path", a.ko.Spec.StartupScriptS3Path, b.ko.Spec.StartupScriptS3Path)
	} else if a.ko.Spec.StartupScriptS3Path != nil && b.ko.Spec.StartupScriptS3Path != nil {
		if *a.ko.Spec.StartupScriptS3Path != *b.ko.Spec.StartupScriptS3Path {
			delta.Add("Spec.StartupScriptS3Path", a.ko.Spec.StartupScriptS3Path, b.ko.Spec.StartupScriptS3Path)
		}
	}
	desiredACKTags, _ := convertToOrderedACKTags(a.ko.Spec.Tags)
	latestACKTags, _ := convertToOrderedACKTags(b.ko.Spec.Tags)
	if !ackcompare.MapStringStringEqual(desiredACKTags, latestACKTags) {
		delta.Add("Spec.Tags", a.ko.Spec.Tags, b.ko.Spec.Tags)
	}
	if ackcompare.HasNilDifference(a.ko.Spec.WebserverAccessMode, b.ko.Spec.WebserverAccessMode) {
		delta.Add("Spec.WebserverAccessMode", a.ko.Spec.WebserverAccessMode, b.ko.Spec.WebserverAccessMode)
	} else if a.ko.Spec.WebserverAccessMode != nil && b.ko.Spec.WebserverAccessMode != nil {
		if *a.ko.Spec.WebserverAccessMode != *b.ko.Spec.WebserverAccessMode {
			delta.Add("Spec.WebserverAccessMode", a.ko.Spec.WebserverAccessMode, b.ko.Spec.WebserverAccessMode)
		}
	}
	if ackcompare.HasNilDifference(a.ko.Spec.WeeklyMaintenanceWindowStart, b.ko.Spec.WeeklyMaintenanceWindowStart) {
		delta.Add("Spec.WeeklyMaintenanceWindowStart", a.ko.Spec.WeeklyMaintenanceWindowStart, b.ko.Spec.WeeklyMaintenanceWindowStart)
	} else if a.ko.Spec.WeeklyMaintenanceWindowStart != nil && b.ko.Spec.WeeklyMaintenanceWindowStart != nil {
		if *a.ko.Spec.WeeklyMaintenanceWindowStart != *b.ko.Spec.WeeklyMaintenanceWindowStart {
			delta.Add("Spec.WeeklyMaintenanceWindowStart", a.ko.Spec.WeeklyMaintenanceWindowStart, b.ko.Spec.WeeklyMaintenanceWindowStart)
		}
	}

	return delta
}
