// Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License"). You may
// not use this file except in compliance with the License. A copy of the
// License is located at
//
//     http://aws.amazon.com/apache2.0/
//
// or in the "license" file accompanying this file. This file is distributed
// on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
// express or implied. See the License for the specific language governing
// permissions and limitations under the License.

// Code generated by ack-generate. DO NOT EDIT.

package environment

import (
	"context"
	"errors"
	"fmt"
	"math"
	"reflect"
	"strings"

	ackv1alpha1 "github.com/aws-controllers-k8s/runtime/apis/core/v1alpha1"
	ackcompare "github.com/aws-controllers-k8s/runtime/pkg/compare"
	ackcondition "github.com/aws-controllers-k8s/runtime/pkg/condition"
	ackerr "github.com/aws-controllers-k8s/runtime/pkg/errors"
	ackrequeue "github.com/aws-controllers-k8s/runtime/pkg/requeue"
	ackrtlog "github.com/aws-controllers-k8s/runtime/pkg/runtime/log"
	"github.com/aws/aws-sdk-go-v2/aws"
	svcsdk "github.com/aws/aws-sdk-go-v2/service/mwaa"
	svcsdktypes "github.com/aws/aws-sdk-go-v2/service/mwaa/types"
	smithy "github.com/aws/smithy-go"
	corev1 "k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"

	svcapitypes "github.com/aws-controllers-k8s/mwaa-controller/apis/v1alpha1"
)

// Hack to avoid import errors during build...
var (
	_ = &metav1.Time{}
	_ = strings.ToLower("")
	_ = &svcsdk.Client{}
	_ = &svcapitypes.Environment{}
	_ = ackv1alpha1.AWSAccountID("")
	_ = &ackerr.NotFound
	_ = &ackcondition.NotManagedMessage
	_ = &reflect.Value{}
	_ = fmt.Sprintf("")
	_ = &ackrequeue.NoRequeue{}
	_ = &aws.Config{}
)

// sdkFind returns SDK-specific information about a supplied resource
func (rm *resourceManager) sdkFind(
	ctx context.Context,
	r *resource,
) (latest *resource, err error) {
	rlog := ackrtlog.FromContext(ctx)
	exit := rlog.Trace("rm.sdkFind")
	defer func() {
		exit(err)
	}()
	// If any required fields in the input shape are missing, AWS resource is
	// not created yet. Return NotFound here to indicate to callers that the
	// resource isn't yet created.
	if rm.requiredFieldsMissingFromReadOneInput(r) {
		return nil, ackerr.NotFound
	}

	input, err := rm.newDescribeRequestPayload(r)
	if err != nil {
		return nil, err
	}

	var resp *svcsdk.GetEnvironmentOutput
	resp, err = rm.sdkapi.GetEnvironment(ctx, input)
	rm.metrics.RecordAPICall("READ_ONE", "GetEnvironment", err)
	if err != nil {
		var awsErr smithy.APIError
		if errors.As(err, &awsErr) && awsErr.ErrorCode() == "ResourceNotFoundException" {
			return nil, ackerr.NotFound
		}
		return nil, err
	}

	// Merge in the information we read from the API call above to the copy of
	// the original Kubernetes object we passed to the function
	ko := r.ko.DeepCopy()

	if resp.Environment.AirflowConfigurationOptions != nil {
		ko.Spec.AirflowConfigurationOptions = aws.StringMap(resp.Environment.AirflowConfigurationOptions)
	} else {
		ko.Spec.AirflowConfigurationOptions = nil
	}
	if resp.Environment.AirflowVersion != nil {
		ko.Spec.AirflowVersion = resp.Environment.AirflowVersion
	} else {
		ko.Spec.AirflowVersion = nil
	}
	if ko.Status.ACKResourceMetadata == nil {
		ko.Status.ACKResourceMetadata = &ackv1alpha1.ResourceMetadata{}
	}
	if resp.Environment.Arn != nil {
		arn := ackv1alpha1.AWSResourceName(*resp.Environment.Arn)
		ko.Status.ACKResourceMetadata.ARN = &arn
	}
	if resp.Environment.CreatedAt != nil {
		ko.Status.CreatedAt = &metav1.Time{*resp.Environment.CreatedAt}
	} else {
		ko.Status.CreatedAt = nil
	}
	if resp.Environment.DagS3Path != nil {
		ko.Spec.DagS3Path = resp.Environment.DagS3Path
	} else {
		ko.Spec.DagS3Path = nil
	}
	if resp.Environment.EndpointManagement != "" {
		ko.Spec.EndpointManagement = aws.String(string(resp.Environment.EndpointManagement))
	} else {
		ko.Spec.EndpointManagement = nil
	}
	if resp.Environment.EnvironmentClass != nil {
		ko.Spec.EnvironmentClass = resp.Environment.EnvironmentClass
	} else {
		ko.Spec.EnvironmentClass = nil
	}
	if resp.Environment.ExecutionRoleArn != nil {
		ko.Spec.ExecutionRoleARN = resp.Environment.ExecutionRoleArn
	} else {
		ko.Spec.ExecutionRoleARN = nil
	}
	if resp.Environment.KmsKey != nil {
		ko.Spec.KMSKey = resp.Environment.KmsKey
	} else {
		ko.Spec.KMSKey = nil
	}
	if resp.Environment.LoggingConfiguration != nil {
		f12 := &svcapitypes.LoggingConfigurationInput{}
		if resp.Environment.LoggingConfiguration.DagProcessingLogs != nil {
			f12f0 := &svcapitypes.ModuleLoggingConfigurationInput{}
			if resp.Environment.LoggingConfiguration.DagProcessingLogs.Enabled != nil {
				f12f0.Enabled = resp.Environment.LoggingConfiguration.DagProcessingLogs.Enabled
			}
			if resp.Environment.LoggingConfiguration.DagProcessingLogs.LogLevel != "" {
				f12f0.LogLevel = aws.String(string(resp.Environment.LoggingConfiguration.DagProcessingLogs.LogLevel))
			}
			f12.DagProcessingLogs = f12f0
		}
		if resp.Environment.LoggingConfiguration.SchedulerLogs != nil {
			f12f1 := &svcapitypes.ModuleLoggingConfigurationInput{}
			if resp.Environment.LoggingConfiguration.SchedulerLogs.Enabled != nil {
				f12f1.Enabled = resp.Environment.LoggingConfiguration.SchedulerLogs.Enabled
			}
			if resp.Environment.LoggingConfiguration.SchedulerLogs.LogLevel != "" {
				f12f1.LogLevel = aws.String(string(resp.Environment.LoggingConfiguration.SchedulerLogs.LogLevel))
			}
			f12.SchedulerLogs = f12f1
		}
		if resp.Environment.LoggingConfiguration.TaskLogs != nil {
			f12f2 := &svcapitypes.ModuleLoggingConfigurationInput{}
			if resp.Environment.LoggingConfiguration.TaskLogs.Enabled != nil {
				f12f2.Enabled = resp.Environment.LoggingConfiguration.TaskLogs.Enabled
			}
			if resp.Environment.LoggingConfiguration.TaskLogs.LogLevel != "" {
				f12f2.LogLevel = aws.String(string(resp.Environment.LoggingConfiguration.TaskLogs.LogLevel))
			}
			f12.TaskLogs = f12f2
		}
		if resp.Environment.LoggingConfiguration.WebserverLogs != nil {
			f12f3 := &svcapitypes.ModuleLoggingConfigurationInput{}
			if resp.Environment.LoggingConfiguration.WebserverLogs.Enabled != nil {
				f12f3.Enabled = resp.Environment.LoggingConfiguration.WebserverLogs.Enabled
			}
			if resp.Environment.LoggingConfiguration.WebserverLogs.LogLevel != "" {
				f12f3.LogLevel = aws.String(string(resp.Environment.LoggingConfiguration.WebserverLogs.LogLevel))
			}
			f12.WebserverLogs = f12f3
		}
		if resp.Environment.LoggingConfiguration.WorkerLogs != nil {
			f12f4 := &svcapitypes.ModuleLoggingConfigurationInput{}
			if resp.Environment.LoggingConfiguration.WorkerLogs.Enabled != nil {
				f12f4.Enabled = resp.Environment.LoggingConfiguration.WorkerLogs.Enabled
			}
			if resp.Environment.LoggingConfiguration.WorkerLogs.LogLevel != "" {
				f12f4.LogLevel = aws.String(string(resp.Environment.LoggingConfiguration.WorkerLogs.LogLevel))
			}
			f12.WorkerLogs = f12f4
		}
		ko.Spec.LoggingConfiguration = f12
	} else {
		ko.Spec.LoggingConfiguration = nil
	}
	if resp.Environment.MaxWebservers != nil {
		maxWebserversCopy := int64(*resp.Environment.MaxWebservers)
		ko.Spec.MaxWebservers = &maxWebserversCopy
	} else {
		ko.Spec.MaxWebservers = nil
	}
	if resp.Environment.MaxWorkers != nil {
		maxWorkersCopy := int64(*resp.Environment.MaxWorkers)
		ko.Spec.MaxWorkers = &maxWorkersCopy
	} else {
		ko.Spec.MaxWorkers = nil
	}
	if resp.Environment.MinWebservers != nil {
		minWebserversCopy := int64(*resp.Environment.MinWebservers)
		ko.Spec.MinWebservers = &minWebserversCopy
	} else {
		ko.Spec.MinWebservers = nil
	}
	if resp.Environment.MinWorkers != nil {
		minWorkersCopy := int64(*resp.Environment.MinWorkers)
		ko.Spec.MinWorkers = &minWorkersCopy
	} else {
		ko.Spec.MinWorkers = nil
	}
	if resp.Environment.Name != nil {
		ko.Spec.Name = resp.Environment.Name
	} else {
		ko.Spec.Name = nil
	}
	if resp.Environment.NetworkConfiguration != nil {
		f18 := &svcapitypes.NetworkConfiguration{}
		if resp.Environment.NetworkConfiguration.SecurityGroupIds != nil {
			f18.SecurityGroupIDs = aws.StringSlice(resp.Environment.NetworkConfiguration.SecurityGroupIds)
		}
		if resp.Environment.NetworkConfiguration.SubnetIds != nil {
			f18.SubnetIDs = aws.StringSlice(resp.Environment.NetworkConfiguration.SubnetIds)
		}
		ko.Spec.NetworkConfiguration = f18
	} else {
		ko.Spec.NetworkConfiguration = nil
	}
	if resp.Environment.PluginsS3ObjectVersion != nil {
		ko.Spec.PluginsS3ObjectVersion = resp.Environment.PluginsS3ObjectVersion
	} else {
		ko.Spec.PluginsS3ObjectVersion = nil
	}
	if resp.Environment.PluginsS3Path != nil {
		ko.Spec.PluginsS3Path = resp.Environment.PluginsS3Path
	} else {
		ko.Spec.PluginsS3Path = nil
	}
	if resp.Environment.RequirementsS3ObjectVersion != nil {
		ko.Spec.RequirementsS3ObjectVersion = resp.Environment.RequirementsS3ObjectVersion
	} else {
		ko.Spec.RequirementsS3ObjectVersion = nil
	}
	if resp.Environment.RequirementsS3Path != nil {
		ko.Spec.RequirementsS3Path = resp.Environment.RequirementsS3Path
	} else {
		ko.Spec.RequirementsS3Path = nil
	}
	if resp.Environment.Schedulers != nil {
		schedulersCopy := int64(*resp.Environment.Schedulers)
		ko.Spec.Schedulers = &schedulersCopy
	} else {
		ko.Spec.Schedulers = nil
	}
	if resp.Environment.SourceBucketArn != nil {
		ko.Spec.SourceBucketARN = resp.Environment.SourceBucketArn
	} else {
		ko.Spec.SourceBucketARN = nil
	}
	if resp.Environment.StartupScriptS3ObjectVersion != nil {
		ko.Spec.StartupScriptS3ObjectVersion = resp.Environment.StartupScriptS3ObjectVersion
	} else {
		ko.Spec.StartupScriptS3ObjectVersion = nil
	}
	if resp.Environment.StartupScriptS3Path != nil {
		ko.Spec.StartupScriptS3Path = resp.Environment.StartupScriptS3Path
	} else {
		ko.Spec.StartupScriptS3Path = nil
	}
	if resp.Environment.Status != "" {
		ko.Status.Status = aws.String(string(resp.Environment.Status))
	} else {
		ko.Status.Status = nil
	}
	if resp.Environment.Tags != nil {
		ko.Spec.Tags = aws.StringMap(resp.Environment.Tags)
	} else {
		ko.Spec.Tags = nil
	}
	if resp.Environment.WebserverAccessMode != "" {
		ko.Spec.WebserverAccessMode = aws.String(string(resp.Environment.WebserverAccessMode))
	} else {
		ko.Spec.WebserverAccessMode = nil
	}
	if resp.Environment.WebserverUrl != nil {
		ko.Status.WebserverURL = resp.Environment.WebserverUrl
	} else {
		ko.Status.WebserverURL = nil
	}
	if resp.Environment.WeeklyMaintenanceWindowStart != nil {
		ko.Spec.WeeklyMaintenanceWindowStart = resp.Environment.WeeklyMaintenanceWindowStart
	} else {
		ko.Spec.WeeklyMaintenanceWindowStart = nil
	}

	rm.setStatusDefaults(ko)
	// AirflowConfigurationOptions: GetEnvironment returns redacted values
	// ("***") for sensitive config options. Preserve the desired values to
	// prevent false drift detection and infinite update loops.
	if r.ko.Spec.AirflowConfigurationOptions != nil {
		ko.Spec.AirflowConfigurationOptions = r.ko.Spec.AirflowConfigurationOptions
	}

	// Return terminal error for failure states so updateConditions preserves it.
	// NOTE: UPDATE_FAILED is intentionally excluded — MWAA rolls back to the
	// previous configuration and the environment returns to AVAILABLE, so the
	// controller should requeue and let the user fix their spec.
	if ko.Status.Status != nil {
		status := *ko.Status.Status
		if status == string(svcsdktypes.EnvironmentStatusCreateFailed) ||
			status == string(svcsdktypes.EnvironmentStatusUnavailable) {
			return &resource{ko}, ackerr.NewTerminalError(
				fmt.Errorf("environment is in terminal state: %s", status),
			)
		}
	}

	return &resource{ko}, nil
}

// requiredFieldsMissingFromReadOneInput returns true if there are any fields
// for the ReadOne Input shape that are required but not present in the
// resource's Spec or Status
func (rm *resourceManager) requiredFieldsMissingFromReadOneInput(
	r *resource,
) bool {
	return r.ko.Spec.Name == nil

}

// newDescribeRequestPayload returns SDK-specific struct for the HTTP request
// payload of the Describe API call for the resource
func (rm *resourceManager) newDescribeRequestPayload(
	r *resource,
) (*svcsdk.GetEnvironmentInput, error) {
	res := &svcsdk.GetEnvironmentInput{}

	if r.ko.Spec.Name != nil {
		res.Name = r.ko.Spec.Name
	}

	return res, nil
}

// sdkCreate creates the supplied resource in the backend AWS service API and
// returns a copy of the resource with resource fields (in both Spec and
// Status) filled in with values from the CREATE API operation's Output shape.
func (rm *resourceManager) sdkCreate(
	ctx context.Context,
	desired *resource,
) (created *resource, err error) {
	rlog := ackrtlog.FromContext(ctx)
	exit := rlog.Trace("rm.sdkCreate")
	defer func() {
		exit(err)
	}()
	input, err := rm.newCreateRequestPayload(ctx, desired)
	if err != nil {
		return nil, err
	}

	var resp *svcsdk.CreateEnvironmentOutput
	_ = resp
	resp, err = rm.sdkapi.CreateEnvironment(ctx, input)
	rm.metrics.RecordAPICall("CREATE", "CreateEnvironment", err)
	if err != nil {
		return nil, err
	}
	// Merge in the information we read from the API call above to the copy of
	// the original Kubernetes object we passed to the function
	ko := desired.ko.DeepCopy()

	if ko.Status.ACKResourceMetadata == nil {
		ko.Status.ACKResourceMetadata = &ackv1alpha1.ResourceMetadata{}
	}
	if resp.Arn != nil {
		arn := ackv1alpha1.AWSResourceName(*resp.Arn)
		ko.Status.ACKResourceMetadata.ARN = &arn
	}

	rm.setStatusDefaults(ko)
	return &resource{ko}, nil
}

// newCreateRequestPayload returns an SDK-specific struct for the HTTP request
// payload of the Create API call for the resource
func (rm *resourceManager) newCreateRequestPayload(
	ctx context.Context,
	r *resource,
) (*svcsdk.CreateEnvironmentInput, error) {
	res := &svcsdk.CreateEnvironmentInput{}

	if r.ko.Spec.AirflowConfigurationOptions != nil {
		res.AirflowConfigurationOptions = aws.ToStringMap(r.ko.Spec.AirflowConfigurationOptions)
	}
	if r.ko.Spec.AirflowVersion != nil {
		res.AirflowVersion = r.ko.Spec.AirflowVersion
	}
	if r.ko.Spec.DagS3Path != nil {
		res.DagS3Path = r.ko.Spec.DagS3Path
	}
	if r.ko.Spec.EndpointManagement != nil {
		res.EndpointManagement = svcsdktypes.EndpointManagement(*r.ko.Spec.EndpointManagement)
	}
	if r.ko.Spec.EnvironmentClass != nil {
		res.EnvironmentClass = r.ko.Spec.EnvironmentClass
	}
	if r.ko.Spec.ExecutionRoleARN != nil {
		res.ExecutionRoleArn = r.ko.Spec.ExecutionRoleARN
	}
	if r.ko.Spec.KMSKey != nil {
		res.KmsKey = r.ko.Spec.KMSKey
	}
	if r.ko.Spec.LoggingConfiguration != nil {
		f7 := &svcsdktypes.LoggingConfigurationInput{}
		if r.ko.Spec.LoggingConfiguration.DagProcessingLogs != nil {
			f7f0 := &svcsdktypes.ModuleLoggingConfigurationInput{}
			if r.ko.Spec.LoggingConfiguration.DagProcessingLogs.Enabled != nil {
				f7f0.Enabled = r.ko.Spec.LoggingConfiguration.DagProcessingLogs.Enabled
			}
			if r.ko.Spec.LoggingConfiguration.DagProcessingLogs.LogLevel != nil {
				f7f0.LogLevel = svcsdktypes.LoggingLevel(*r.ko.Spec.LoggingConfiguration.DagProcessingLogs.LogLevel)
			}
			f7.DagProcessingLogs = f7f0
		}
		if r.ko.Spec.LoggingConfiguration.SchedulerLogs != nil {
			f7f1 := &svcsdktypes.ModuleLoggingConfigurationInput{}
			if r.ko.Spec.LoggingConfiguration.SchedulerLogs.Enabled != nil {
				f7f1.Enabled = r.ko.Spec.LoggingConfiguration.SchedulerLogs.Enabled
			}
			if r.ko.Spec.LoggingConfiguration.SchedulerLogs.LogLevel != nil {
				f7f1.LogLevel = svcsdktypes.LoggingLevel(*r.ko.Spec.LoggingConfiguration.SchedulerLogs.LogLevel)
			}
			f7.SchedulerLogs = f7f1
		}
		if r.ko.Spec.LoggingConfiguration.TaskLogs != nil {
			f7f2 := &svcsdktypes.ModuleLoggingConfigurationInput{}
			if r.ko.Spec.LoggingConfiguration.TaskLogs.Enabled != nil {
				f7f2.Enabled = r.ko.Spec.LoggingConfiguration.TaskLogs.Enabled
			}
			if r.ko.Spec.LoggingConfiguration.TaskLogs.LogLevel != nil {
				f7f2.LogLevel = svcsdktypes.LoggingLevel(*r.ko.Spec.LoggingConfiguration.TaskLogs.LogLevel)
			}
			f7.TaskLogs = f7f2
		}
		if r.ko.Spec.LoggingConfiguration.WebserverLogs != nil {
			f7f3 := &svcsdktypes.ModuleLoggingConfigurationInput{}
			if r.ko.Spec.LoggingConfiguration.WebserverLogs.Enabled != nil {
				f7f3.Enabled = r.ko.Spec.LoggingConfiguration.WebserverLogs.Enabled
			}
			if r.ko.Spec.LoggingConfiguration.WebserverLogs.LogLevel != nil {
				f7f3.LogLevel = svcsdktypes.LoggingLevel(*r.ko.Spec.LoggingConfiguration.WebserverLogs.LogLevel)
			}
			f7.WebserverLogs = f7f3
		}
		if r.ko.Spec.LoggingConfiguration.WorkerLogs != nil {
			f7f4 := &svcsdktypes.ModuleLoggingConfigurationInput{}
			if r.ko.Spec.LoggingConfiguration.WorkerLogs.Enabled != nil {
				f7f4.Enabled = r.ko.Spec.LoggingConfiguration.WorkerLogs.Enabled
			}
			if r.ko.Spec.LoggingConfiguration.WorkerLogs.LogLevel != nil {
				f7f4.LogLevel = svcsdktypes.LoggingLevel(*r.ko.Spec.LoggingConfiguration.WorkerLogs.LogLevel)
			}
			f7.WorkerLogs = f7f4
		}
		res.LoggingConfiguration = f7
	}
	if r.ko.Spec.MaxWebservers != nil {
		maxWebserversCopy0 := *r.ko.Spec.MaxWebservers
		if maxWebserversCopy0 > math.MaxInt32 || maxWebserversCopy0 < math.MinInt32 {
			return nil, fmt.Errorf("error: field MaxWebservers is of type int32")
		}
		maxWebserversCopy := int32(maxWebserversCopy0)
		res.MaxWebservers = &maxWebserversCopy
	}
	if r.ko.Spec.MaxWorkers != nil {
		maxWorkersCopy0 := *r.ko.Spec.MaxWorkers
		if maxWorkersCopy0 > math.MaxInt32 || maxWorkersCopy0 < math.MinInt32 {
			return nil, fmt.Errorf("error: field MaxWorkers is of type int32")
		}
		maxWorkersCopy := int32(maxWorkersCopy0)
		res.MaxWorkers = &maxWorkersCopy
	}
	if r.ko.Spec.MinWebservers != nil {
		minWebserversCopy0 := *r.ko.Spec.MinWebservers
		if minWebserversCopy0 > math.MaxInt32 || minWebserversCopy0 < math.MinInt32 {
			return nil, fmt.Errorf("error: field MinWebservers is of type int32")
		}
		minWebserversCopy := int32(minWebserversCopy0)
		res.MinWebservers = &minWebserversCopy
	}
	if r.ko.Spec.MinWorkers != nil {
		minWorkersCopy0 := *r.ko.Spec.MinWorkers
		if minWorkersCopy0 > math.MaxInt32 || minWorkersCopy0 < math.MinInt32 {
			return nil, fmt.Errorf("error: field MinWorkers is of type int32")
		}
		minWorkersCopy := int32(minWorkersCopy0)
		res.MinWorkers = &minWorkersCopy
	}
	if r.ko.Spec.Name != nil {
		res.Name = r.ko.Spec.Name
	}
	if r.ko.Spec.NetworkConfiguration != nil {
		f13 := &svcsdktypes.NetworkConfiguration{}
		if r.ko.Spec.NetworkConfiguration.SecurityGroupIDs != nil {
			f13.SecurityGroupIds = aws.ToStringSlice(r.ko.Spec.NetworkConfiguration.SecurityGroupIDs)
		}
		if r.ko.Spec.NetworkConfiguration.SubnetIDs != nil {
			f13.SubnetIds = aws.ToStringSlice(r.ko.Spec.NetworkConfiguration.SubnetIDs)
		}
		res.NetworkConfiguration = f13
	}
	if r.ko.Spec.PluginsS3ObjectVersion != nil {
		res.PluginsS3ObjectVersion = r.ko.Spec.PluginsS3ObjectVersion
	}
	if r.ko.Spec.PluginsS3Path != nil {
		res.PluginsS3Path = r.ko.Spec.PluginsS3Path
	}
	if r.ko.Spec.RequirementsS3ObjectVersion != nil {
		res.RequirementsS3ObjectVersion = r.ko.Spec.RequirementsS3ObjectVersion
	}
	if r.ko.Spec.RequirementsS3Path != nil {
		res.RequirementsS3Path = r.ko.Spec.RequirementsS3Path
	}
	if r.ko.Spec.Schedulers != nil {
		schedulersCopy0 := *r.ko.Spec.Schedulers
		if schedulersCopy0 > math.MaxInt32 || schedulersCopy0 < math.MinInt32 {
			return nil, fmt.Errorf("error: field Schedulers is of type int32")
		}
		schedulersCopy := int32(schedulersCopy0)
		res.Schedulers = &schedulersCopy
	}
	if r.ko.Spec.SourceBucketARN != nil {
		res.SourceBucketArn = r.ko.Spec.SourceBucketARN
	}
	if r.ko.Spec.StartupScriptS3ObjectVersion != nil {
		res.StartupScriptS3ObjectVersion = r.ko.Spec.StartupScriptS3ObjectVersion
	}
	if r.ko.Spec.StartupScriptS3Path != nil {
		res.StartupScriptS3Path = r.ko.Spec.StartupScriptS3Path
	}
	if r.ko.Spec.Tags != nil {
		res.Tags = aws.ToStringMap(r.ko.Spec.Tags)
	}
	if r.ko.Spec.WebserverAccessMode != nil {
		res.WebserverAccessMode = svcsdktypes.WebserverAccessMode(*r.ko.Spec.WebserverAccessMode)
	}
	if r.ko.Spec.WeeklyMaintenanceWindowStart != nil {
		res.WeeklyMaintenanceWindowStart = r.ko.Spec.WeeklyMaintenanceWindowStart
	}

	return res, nil
}

// sdkUpdate patches the supplied resource in the backend AWS service API and
// returns a new resource with updated fields.
func (rm *resourceManager) sdkUpdate(
	ctx context.Context,
	desired *resource,
	latest *resource,
	delta *ackcompare.Delta,
) (updated *resource, err error) {
	rlog := ackrtlog.FromContext(ctx)
	exit := rlog.Trace("rm.sdkUpdate")
	defer func() {
		exit(err)
	}()
	// Don't attempt updates while the environment is in a transitional state.
	// MWAA rejects updates unless the environment is AVAILABLE.
	if latest.ko.Status.Status != nil {
		status := *latest.ko.Status.Status
		if status != string(svcsdktypes.EnvironmentStatusAvailable) {
			return nil, ackrequeue.NeededAfter(
				fmt.Errorf("environment is in %s state, cannot update until AVAILABLE", status),
				ackrequeue.DefaultRequeueAfterDuration,
			)
		}
	}

	input, err := rm.newUpdateRequestPayload(ctx, desired, delta)
	if err != nil {
		return nil, err
	}

	var resp *svcsdk.UpdateEnvironmentOutput
	_ = resp
	resp, err = rm.sdkapi.UpdateEnvironment(ctx, input)
	rm.metrics.RecordAPICall("UPDATE", "UpdateEnvironment", err)
	if err != nil {
		return nil, err
	}
	// Merge in the information we read from the API call above to the copy of
	// the original Kubernetes object we passed to the function
	ko := desired.ko.DeepCopy()

	if ko.Status.ACKResourceMetadata == nil {
		ko.Status.ACKResourceMetadata = &ackv1alpha1.ResourceMetadata{}
	}
	if resp.Arn != nil {
		arn := ackv1alpha1.AWSResourceName(*resp.Arn)
		ko.Status.ACKResourceMetadata.ARN = &arn
	}

	rm.setStatusDefaults(ko)
	return &resource{ko}, nil
}

// newUpdateRequestPayload returns an SDK-specific struct for the HTTP request
// payload of the Update API call for the resource
func (rm *resourceManager) newUpdateRequestPayload(
	ctx context.Context,
	r *resource,
	delta *ackcompare.Delta,
) (*svcsdk.UpdateEnvironmentInput, error) {
	res := &svcsdk.UpdateEnvironmentInput{}

	if r.ko.Spec.AirflowConfigurationOptions != nil {
		res.AirflowConfigurationOptions = aws.ToStringMap(r.ko.Spec.AirflowConfigurationOptions)
	}
	if r.ko.Spec.AirflowVersion != nil {
		res.AirflowVersion = r.ko.Spec.AirflowVersion
	}
	if r.ko.Spec.DagS3Path != nil {
		res.DagS3Path = r.ko.Spec.DagS3Path
	}
	if r.ko.Spec.EnvironmentClass != nil {
		res.EnvironmentClass = r.ko.Spec.EnvironmentClass
	}
	if r.ko.Spec.ExecutionRoleARN != nil {
		res.ExecutionRoleArn = r.ko.Spec.ExecutionRoleARN
	}
	if r.ko.Spec.LoggingConfiguration != nil {
		f5 := &svcsdktypes.LoggingConfigurationInput{}
		if r.ko.Spec.LoggingConfiguration.DagProcessingLogs != nil {
			f5f0 := &svcsdktypes.ModuleLoggingConfigurationInput{}
			if r.ko.Spec.LoggingConfiguration.DagProcessingLogs.Enabled != nil {
				f5f0.Enabled = r.ko.Spec.LoggingConfiguration.DagProcessingLogs.Enabled
			}
			if r.ko.Spec.LoggingConfiguration.DagProcessingLogs.LogLevel != nil {
				f5f0.LogLevel = svcsdktypes.LoggingLevel(*r.ko.Spec.LoggingConfiguration.DagProcessingLogs.LogLevel)
			}
			f5.DagProcessingLogs = f5f0
		}
		if r.ko.Spec.LoggingConfiguration.SchedulerLogs != nil {
			f5f1 := &svcsdktypes.ModuleLoggingConfigurationInput{}
			if r.ko.Spec.LoggingConfiguration.SchedulerLogs.Enabled != nil {
				f5f1.Enabled = r.ko.Spec.LoggingConfiguration.SchedulerLogs.Enabled
			}
			if r.ko.Spec.LoggingConfiguration.SchedulerLogs.LogLevel != nil {
				f5f1.LogLevel = svcsdktypes.LoggingLevel(*r.ko.Spec.LoggingConfiguration.SchedulerLogs.LogLevel)
			}
			f5.SchedulerLogs = f5f1
		}
		if r.ko.Spec.LoggingConfiguration.TaskLogs != nil {
			f5f2 := &svcsdktypes.ModuleLoggingConfigurationInput{}
			if r.ko.Spec.LoggingConfiguration.TaskLogs.Enabled != nil {
				f5f2.Enabled = r.ko.Spec.LoggingConfiguration.TaskLogs.Enabled
			}
			if r.ko.Spec.LoggingConfiguration.TaskLogs.LogLevel != nil {
				f5f2.LogLevel = svcsdktypes.LoggingLevel(*r.ko.Spec.LoggingConfiguration.TaskLogs.LogLevel)
			}
			f5.TaskLogs = f5f2
		}
		if r.ko.Spec.LoggingConfiguration.WebserverLogs != nil {
			f5f3 := &svcsdktypes.ModuleLoggingConfigurationInput{}
			if r.ko.Spec.LoggingConfiguration.WebserverLogs.Enabled != nil {
				f5f3.Enabled = r.ko.Spec.LoggingConfiguration.WebserverLogs.Enabled
			}
			if r.ko.Spec.LoggingConfiguration.WebserverLogs.LogLevel != nil {
				f5f3.LogLevel = svcsdktypes.LoggingLevel(*r.ko.Spec.LoggingConfiguration.WebserverLogs.LogLevel)
			}
			f5.WebserverLogs = f5f3
		}
		if r.ko.Spec.LoggingConfiguration.WorkerLogs != nil {
			f5f4 := &svcsdktypes.ModuleLoggingConfigurationInput{}
			if r.ko.Spec.LoggingConfiguration.WorkerLogs.Enabled != nil {
				f5f4.Enabled = r.ko.Spec.LoggingConfiguration.WorkerLogs.Enabled
			}
			if r.ko.Spec.LoggingConfiguration.WorkerLogs.LogLevel != nil {
				f5f4.LogLevel = svcsdktypes.LoggingLevel(*r.ko.Spec.LoggingConfiguration.WorkerLogs.LogLevel)
			}
			f5.WorkerLogs = f5f4
		}
		res.LoggingConfiguration = f5
	}
	if r.ko.Spec.MaxWebservers != nil {
		maxWebserversCopy0 := *r.ko.Spec.MaxWebservers
		if maxWebserversCopy0 > math.MaxInt32 || maxWebserversCopy0 < math.MinInt32 {
			return nil, fmt.Errorf("error: field MaxWebservers is of type int32")
		}
		maxWebserversCopy := int32(maxWebserversCopy0)
		res.MaxWebservers = &maxWebserversCopy
	}
	if r.ko.Spec.MaxWorkers != nil {
		maxWorkersCopy0 := *r.ko.Spec.MaxWorkers
		if maxWorkersCopy0 > math.MaxInt32 || maxWorkersCopy0 < math.MinInt32 {
			return nil, fmt.Errorf("error: field MaxWorkers is of type int32")
		}
		maxWorkersCopy := int32(maxWorkersCopy0)
		res.MaxWorkers = &maxWorkersCopy
	}
	if r.ko.Spec.MinWebservers != nil {
		minWebserversCopy0 := *r.ko.Spec.MinWebservers
		if minWebserversCopy0 > math.MaxInt32 || minWebserversCopy0 < math.MinInt32 {
			return nil, fmt.Errorf("error: field MinWebservers is of type int32")
		}
		minWebserversCopy := int32(minWebserversCopy0)
		res.MinWebservers = &minWebserversCopy
	}
	if r.ko.Spec.MinWorkers != nil {
		minWorkersCopy0 := *r.ko.Spec.MinWorkers
		if minWorkersCopy0 > math.MaxInt32 || minWorkersCopy0 < math.MinInt32 {
			return nil, fmt.Errorf("error: field MinWorkers is of type int32")
		}
		minWorkersCopy := int32(minWorkersCopy0)
		res.MinWorkers = &minWorkersCopy
	}
	if r.ko.Spec.Name != nil {
		res.Name = r.ko.Spec.Name
	}
	if r.ko.Spec.NetworkConfiguration != nil {
		f11 := &svcsdktypes.UpdateNetworkConfigurationInput{}
		if r.ko.Spec.NetworkConfiguration.SecurityGroupIDs != nil {
			f11.SecurityGroupIds = aws.ToStringSlice(r.ko.Spec.NetworkConfiguration.SecurityGroupIDs)
		}
		res.NetworkConfiguration = f11
	}
	if r.ko.Spec.PluginsS3ObjectVersion != nil {
		res.PluginsS3ObjectVersion = r.ko.Spec.PluginsS3ObjectVersion
	}
	if r.ko.Spec.PluginsS3Path != nil {
		res.PluginsS3Path = r.ko.Spec.PluginsS3Path
	}
	if r.ko.Spec.RequirementsS3ObjectVersion != nil {
		res.RequirementsS3ObjectVersion = r.ko.Spec.RequirementsS3ObjectVersion
	}
	if r.ko.Spec.RequirementsS3Path != nil {
		res.RequirementsS3Path = r.ko.Spec.RequirementsS3Path
	}
	if r.ko.Spec.Schedulers != nil {
		schedulersCopy0 := *r.ko.Spec.Schedulers
		if schedulersCopy0 > math.MaxInt32 || schedulersCopy0 < math.MinInt32 {
			return nil, fmt.Errorf("error: field Schedulers is of type int32")
		}
		schedulersCopy := int32(schedulersCopy0)
		res.Schedulers = &schedulersCopy
	}
	if r.ko.Spec.SourceBucketARN != nil {
		res.SourceBucketArn = r.ko.Spec.SourceBucketARN
	}
	if r.ko.Spec.StartupScriptS3ObjectVersion != nil {
		res.StartupScriptS3ObjectVersion = r.ko.Spec.StartupScriptS3ObjectVersion
	}
	if r.ko.Spec.StartupScriptS3Path != nil {
		res.StartupScriptS3Path = r.ko.Spec.StartupScriptS3Path
	}
	if r.ko.Spec.WebserverAccessMode != nil {
		res.WebserverAccessMode = svcsdktypes.WebserverAccessMode(*r.ko.Spec.WebserverAccessMode)
	}
	if r.ko.Spec.WeeklyMaintenanceWindowStart != nil {
		res.WeeklyMaintenanceWindowStart = r.ko.Spec.WeeklyMaintenanceWindowStart
	}

	return res, nil
}

// sdkDelete deletes the supplied resource in the backend AWS service API
func (rm *resourceManager) sdkDelete(
	ctx context.Context,
	r *resource,
) (latest *resource, err error) {
	rlog := ackrtlog.FromContext(ctx)
	exit := rlog.Trace("rm.sdkDelete")
	defer func() {
		exit(err)
	}()
	input, err := rm.newDeleteRequestPayload(r)
	if err != nil {
		return nil, err
	}
	var resp *svcsdk.DeleteEnvironmentOutput
	_ = resp
	resp, err = rm.sdkapi.DeleteEnvironment(ctx, input)
	rm.metrics.RecordAPICall("DELETE", "DeleteEnvironment", err)
	return nil, err
}

// newDeleteRequestPayload returns an SDK-specific struct for the HTTP request
// payload of the Delete API call for the resource
func (rm *resourceManager) newDeleteRequestPayload(
	r *resource,
) (*svcsdk.DeleteEnvironmentInput, error) {
	res := &svcsdk.DeleteEnvironmentInput{}

	if r.ko.Spec.Name != nil {
		res.Name = r.ko.Spec.Name
	}

	return res, nil
}

// setStatusDefaults sets default properties into supplied custom resource
func (rm *resourceManager) setStatusDefaults(
	ko *svcapitypes.Environment,
) {
	if ko.Status.ACKResourceMetadata == nil {
		ko.Status.ACKResourceMetadata = &ackv1alpha1.ResourceMetadata{}
	}
	if ko.Status.ACKResourceMetadata.Region == nil {
		ko.Status.ACKResourceMetadata.Region = &rm.awsRegion
	}
	if ko.Status.ACKResourceMetadata.OwnerAccountID == nil {
		ko.Status.ACKResourceMetadata.OwnerAccountID = &rm.awsAccountID
	}
	if ko.Status.Conditions == nil {
		ko.Status.Conditions = []*ackv1alpha1.Condition{}
	}
}

// updateConditions returns updated resource, true; if conditions were updated
// else it returns nil, false
func (rm *resourceManager) updateConditions(
	r *resource,
	onSuccess bool,
	err error,
) (*resource, bool) {
	ko := r.ko.DeepCopy()
	rm.setStatusDefaults(ko)

	// Terminal condition
	var terminalCondition *ackv1alpha1.Condition = nil
	var recoverableCondition *ackv1alpha1.Condition = nil
	var syncCondition *ackv1alpha1.Condition = nil
	for _, condition := range ko.Status.Conditions {
		if condition.Type == ackv1alpha1.ConditionTypeTerminal {
			terminalCondition = condition
		}
		if condition.Type == ackv1alpha1.ConditionTypeRecoverable {
			recoverableCondition = condition
		}
		if condition.Type == ackv1alpha1.ConditionTypeResourceSynced {
			syncCondition = condition
		}
	}
	var termError *ackerr.TerminalError
	if rm.terminalAWSError(err) || err == ackerr.SecretTypeNotSupported || err == ackerr.SecretNotFound || errors.As(err, &termError) {
		if terminalCondition == nil {
			terminalCondition = &ackv1alpha1.Condition{
				Type: ackv1alpha1.ConditionTypeTerminal,
			}
			ko.Status.Conditions = append(ko.Status.Conditions, terminalCondition)
		}
		var errorMessage = ""
		if err == ackerr.SecretTypeNotSupported || err == ackerr.SecretNotFound || errors.As(err, &termError) {
			errorMessage = err.Error()
		} else {
			awsErr, _ := ackerr.AWSError(err)
			errorMessage = awsErr.Error()
		}
		terminalCondition.Status = corev1.ConditionTrue
		terminalCondition.Message = &errorMessage
	} else {
		// Clear the terminal condition if no longer present
		if terminalCondition != nil {
			terminalCondition.Status = corev1.ConditionFalse
			terminalCondition.Message = nil
		}
		// Handling Recoverable Conditions
		if err != nil {
			if recoverableCondition == nil {
				// Add a new Condition containing a non-terminal error
				recoverableCondition = &ackv1alpha1.Condition{
					Type: ackv1alpha1.ConditionTypeRecoverable,
				}
				ko.Status.Conditions = append(ko.Status.Conditions, recoverableCondition)
			}
			recoverableCondition.Status = corev1.ConditionTrue
			awsErr, _ := ackerr.AWSError(err)
			errorMessage := err.Error()
			if awsErr != nil {
				errorMessage = awsErr.Error()
			}
			recoverableCondition.Message = &errorMessage
		} else if recoverableCondition != nil {
			recoverableCondition.Status = corev1.ConditionFalse
			recoverableCondition.Message = nil
		}
	}
	if syncCondition == nil && onSuccess {
		syncCondition = &ackv1alpha1.Condition{
			Type:   ackv1alpha1.ConditionTypeResourceSynced,
			Status: corev1.ConditionTrue,
		}
		ko.Status.Conditions = append(ko.Status.Conditions, syncCondition)
	}
	if terminalCondition != nil || recoverableCondition != nil || syncCondition != nil {
		return &resource{ko}, true // updated
	}
	return nil, false // not updated
}

// terminalAWSError returns awserr, true; if the supplied error is an aws Error type
// and if the exception indicates that it is a Terminal exception
// 'Terminal' exception are specified in generator configuration
func (rm *resourceManager) terminalAWSError(err error) bool {
	if err == nil {
		return false
	}

	var terminalErr smithy.APIError
	if !errors.As(err, &terminalErr) {
		return false
	}
	switch terminalErr.ErrorCode() {
	case "AccessDeniedException":
		return true
	default:
		return false
	}
}
