apiVersion: v1
name: mwaa-chart
description: A Helm chart for the ACK service controller for Amazon Managed Workflows for Apache Airflow (MWAA)
version: 0.0.0-non-release-version
appVersion: 0.0.0-non-release-version
home: https://github.com/aws-controllers-k8s/mwaa-controller
icon: https://raw.githubusercontent.com/aws/eks-charts/master/docs/logo/aws.png
sources:
  - https://github.com/aws-controllers-k8s/mwaa-controller
maintainers:
  - name: ACK Admins
    url: https://github.com/orgs/aws-controllers-k8s/teams/ack-admin
  - name: MWAA Admins
    url: https://github.com/orgs/aws-controllers-k8s/teams/mwaa-maintainer
keywords:
  - aws
  - kubernetes
  - mwaa
