//go:build !ignore_autogenerated

// Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License"). You may
// not use this file except in compliance with the License. A copy of the
// License is located at
//
//     http://aws.amazon.com/apache2.0/
//
// or in the "license" file accompanying this file. This file is distributed
// on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
// express or implied. See the License for the specific language governing
// permissions and limitations under the License.

// Code generated by ack-generate. DO NOT EDIT.

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	corev1alpha1 "github.com/aws-controllers-k8s/runtime/apis/core/v1alpha1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Dimension) DeepCopyInto(out *Dimension) {
	*out = *in
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.Value != nil {
		in, out := &in.Value, &out.Value
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Dimension.
func (in *Dimension) DeepCopy() *Dimension {
	if in == nil {
		return nil
	}
	out := new(Dimension)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Environment) DeepCopyInto(out *Environment) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Environment.
func (in *Environment) DeepCopy() *Environment {
	if in == nil {
		return nil
	}
	out := new(Environment)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Environment) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EnvironmentList) DeepCopyInto(out *EnvironmentList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Environment, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EnvironmentList.
func (in *EnvironmentList) DeepCopy() *EnvironmentList {
	if in == nil {
		return nil
	}
	out := new(EnvironmentList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *EnvironmentList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EnvironmentSpec) DeepCopyInto(out *EnvironmentSpec) {
	*out = *in
	if in.AirflowConfigurationOptions != nil {
		in, out := &in.AirflowConfigurationOptions, &out.AirflowConfigurationOptions
		*out = make(map[string]*string, len(*in))
		for key, val := range *in {
			var outVal *string
			if val == nil {
				(*out)[key] = nil
			} else {
				inVal := (*in)[key]
				in, out := &inVal, &outVal
				*out = new(string)
				**out = **in
			}
			(*out)[key] = outVal
		}
	}
	if in.AirflowVersion != nil {
		in, out := &in.AirflowVersion, &out.AirflowVersion
		*out = new(string)
		**out = **in
	}
	if in.DagS3Path != nil {
		in, out := &in.DagS3Path, &out.DagS3Path
		*out = new(string)
		**out = **in
	}
	if in.EndpointManagement != nil {
		in, out := &in.EndpointManagement, &out.EndpointManagement
		*out = new(string)
		**out = **in
	}
	if in.EnvironmentClass != nil {
		in, out := &in.EnvironmentClass, &out.EnvironmentClass
		*out = new(string)
		**out = **in
	}
	if in.ExecutionRoleARN != nil {
		in, out := &in.ExecutionRoleARN, &out.ExecutionRoleARN
		*out = new(string)
		**out = **in
	}
	if in.ExecutionRoleRef != nil {
		in, out := &in.ExecutionRoleRef, &out.ExecutionRoleRef
		*out = new(corev1alpha1.AWSResourceReferenceWrapper)
		(*in).DeepCopyInto(*out)
	}
	if in.KMSKey != nil {
		in, out := &in.KMSKey, &out.KMSKey
		*out = new(string)
		**out = **in
	}
	if in.KMSKeyRef != nil {
		in, out := &in.KMSKeyRef, &out.KMSKeyRef
		*out = new(corev1alpha1.AWSResourceReferenceWrapper)
		(*in).DeepCopyInto(*out)
	}
	if in.LoggingConfiguration != nil {
		in, out := &in.LoggingConfiguration, &out.LoggingConfiguration
		*out = new(LoggingConfigurationInput)
		(*in).DeepCopyInto(*out)
	}
	if in.MaxWebservers != nil {
		in, out := &in.MaxWebservers, &out.MaxWebservers
		*out = new(int64)
		**out = **in
	}
	if in.MaxWorkers != nil {
		in, out := &in.MaxWorkers, &out.MaxWorkers
		*out = new(int64)
		**out = **in
	}
	if in.MinWebservers != nil {
		in, out := &in.MinWebservers, &out.MinWebservers
		*out = new(int64)
		**out = **in
	}
	if in.MinWorkers != nil {
		in, out := &in.MinWorkers, &out.MinWorkers
		*out = new(int64)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.NetworkConfiguration != nil {
		in, out := &in.NetworkConfiguration, &out.NetworkConfiguration
		*out = new(NetworkConfiguration)
		(*in).DeepCopyInto(*out)
	}
	if in.PluginsS3ObjectVersion != nil {
		in, out := &in.PluginsS3ObjectVersion, &out.PluginsS3ObjectVersion
		*out = new(string)
		**out = **in
	}
	if in.PluginsS3Path != nil {
		in, out := &in.PluginsS3Path, &out.PluginsS3Path
		*out = new(string)
		**out = **in
	}
	if in.RequirementsS3ObjectVersion != nil {
		in, out := &in.RequirementsS3ObjectVersion, &out.RequirementsS3ObjectVersion
		*out = new(string)
		**out = **in
	}
	if in.RequirementsS3Path != nil {
		in, out := &in.RequirementsS3Path, &out.RequirementsS3Path
		*out = new(string)
		**out = **in
	}
	if in.Schedulers != nil {
		in, out := &in.Schedulers, &out.Schedulers
		*out = new(int64)
		**out = **in
	}
	if in.SourceBucketARN != nil {
		in, out := &in.SourceBucketARN, &out.SourceBucketARN
		*out = new(string)
		**out = **in
	}
	if in.SourceBucketRef != nil {
		in, out := &in.SourceBucketRef, &out.SourceBucketRef
		*out = new(corev1alpha1.AWSResourceReferenceWrapper)
		(*in).DeepCopyInto(*out)
	}
	if in.StartupScriptS3ObjectVersion != nil {
		in, out := &in.StartupScriptS3ObjectVersion, &out.StartupScriptS3ObjectVersion
		*out = new(string)
		**out = **in
	}
	if in.StartupScriptS3Path != nil {
		in, out := &in.StartupScriptS3Path, &out.StartupScriptS3Path
		*out = new(string)
		**out = **in
	}
	if in.Tags != nil {
		in, out := &in.Tags, &out.Tags
		*out = make(map[string]*string, len(*in))
		for key, val := range *in {
			var outVal *string
			if val == nil {
				(*out)[key] = nil
			} else {
				inVal := (*in)[key]
				in, out := &inVal, &outVal
				*out = new(string)
				**out = **in
			}
			(*out)[key] = outVal
		}
	}
	if in.WebserverAccessMode != nil {
		in, out := &in.WebserverAccessMode, &out.WebserverAccessMode
		*out = new(string)
		**out = **in
	}
	if in.WeeklyMaintenanceWindowStart != nil {
		in, out := &in.WeeklyMaintenanceWindowStart, &out.WeeklyMaintenanceWindowStart
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EnvironmentSpec.
func (in *EnvironmentSpec) DeepCopy() *EnvironmentSpec {
	if in == nil {
		return nil
	}
	out := new(EnvironmentSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EnvironmentStatus) DeepCopyInto(out *EnvironmentStatus) {
	*out = *in
	if in.ACKResourceMetadata != nil {
		in, out := &in.ACKResourceMetadata, &out.ACKResourceMetadata
		*out = new(corev1alpha1.ResourceMetadata)
		(*in).DeepCopyInto(*out)
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]*corev1alpha1.Condition, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(corev1alpha1.Condition)
				(*in).DeepCopyInto(*out)
			}
		}
	}
	if in.CreatedAt != nil {
		in, out := &in.CreatedAt, &out.CreatedAt
		*out = (*in).DeepCopy()
	}
	if in.LastUpdate != nil {
		in, out := &in.LastUpdate, &out.LastUpdate
		*out = new(LastUpdate)
		(*in).DeepCopyInto(*out)
	}
	if in.Status != nil {
		in, out := &in.Status, &out.Status
		*out = new(string)
		**out = **in
	}
	if in.WebserverURL != nil {
		in, out := &in.WebserverURL, &out.WebserverURL
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EnvironmentStatus.
func (in *EnvironmentStatus) DeepCopy() *EnvironmentStatus {
	if in == nil {
		return nil
	}
	out := new(EnvironmentStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Environment_SDK) DeepCopyInto(out *Environment_SDK) {
	*out = *in
	if in.AirflowConfigurationOptions != nil {
		in, out := &in.AirflowConfigurationOptions, &out.AirflowConfigurationOptions
		*out = make(map[string]*string, len(*in))
		for key, val := range *in {
			var outVal *string
			if val == nil {
				(*out)[key] = nil
			} else {
				inVal := (*in)[key]
				in, out := &inVal, &outVal
				*out = new(string)
				**out = **in
			}
			(*out)[key] = outVal
		}
	}
	if in.AirflowVersion != nil {
		in, out := &in.AirflowVersion, &out.AirflowVersion
		*out = new(string)
		**out = **in
	}
	if in.ARN != nil {
		in, out := &in.ARN, &out.ARN
		*out = new(string)
		**out = **in
	}
	if in.CeleryExecutorQueue != nil {
		in, out := &in.CeleryExecutorQueue, &out.CeleryExecutorQueue
		*out = new(string)
		**out = **in
	}
	if in.CreatedAt != nil {
		in, out := &in.CreatedAt, &out.CreatedAt
		*out = (*in).DeepCopy()
	}
	if in.DagS3Path != nil {
		in, out := &in.DagS3Path, &out.DagS3Path
		*out = new(string)
		**out = **in
	}
	if in.DatabaseVPCEndpointService != nil {
		in, out := &in.DatabaseVPCEndpointService, &out.DatabaseVPCEndpointService
		*out = new(string)
		**out = **in
	}
	if in.EndpointManagement != nil {
		in, out := &in.EndpointManagement, &out.EndpointManagement
		*out = new(string)
		**out = **in
	}
	if in.EnvironmentClass != nil {
		in, out := &in.EnvironmentClass, &out.EnvironmentClass
		*out = new(string)
		**out = **in
	}
	if in.ExecutionRoleARN != nil {
		in, out := &in.ExecutionRoleARN, &out.ExecutionRoleARN
		*out = new(string)
		**out = **in
	}
	if in.KMSKey != nil {
		in, out := &in.KMSKey, &out.KMSKey
		*out = new(string)
		**out = **in
	}
	if in.LastUpdate != nil {
		in, out := &in.LastUpdate, &out.LastUpdate
		*out = new(LastUpdate)
		(*in).DeepCopyInto(*out)
	}
	if in.LoggingConfiguration != nil {
		in, out := &in.LoggingConfiguration, &out.LoggingConfiguration
		*out = new(LoggingConfiguration)
		(*in).DeepCopyInto(*out)
	}
	if in.MaxWebservers != nil {
		in, out := &in.MaxWebservers, &out.MaxWebservers
		*out = new(int64)
		**out = **in
	}
	if in.MaxWorkers != nil {
		in, out := &in.MaxWorkers, &out.MaxWorkers
		*out = new(int64)
		**out = **in
	}
	if in.MinWebservers != nil {
		in, out := &in.MinWebservers, &out.MinWebservers
		*out = new(int64)
		**out = **in
	}
	if in.MinWorkers != nil {
		in, out := &in.MinWorkers, &out.MinWorkers
		*out = new(int64)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.NetworkConfiguration != nil {
		in, out := &in.NetworkConfiguration, &out.NetworkConfiguration
		*out = new(NetworkConfiguration)
		(*in).DeepCopyInto(*out)
	}
	if in.PluginsS3ObjectVersion != nil {
		in, out := &in.PluginsS3ObjectVersion, &out.PluginsS3ObjectVersion
		*out = new(string)
		**out = **in
	}
	if in.PluginsS3Path != nil {
		in, out := &in.PluginsS3Path, &out.PluginsS3Path
		*out = new(string)
		**out = **in
	}
	if in.RequirementsS3ObjectVersion != nil {
		in, out := &in.RequirementsS3ObjectVersion, &out.RequirementsS3ObjectVersion
		*out = new(string)
		**out = **in
	}
	if in.RequirementsS3Path != nil {
		in, out := &in.RequirementsS3Path, &out.RequirementsS3Path
		*out = new(string)
		**out = **in
	}
	if in.Schedulers != nil {
		in, out := &in.Schedulers, &out.Schedulers
		*out = new(int64)
		**out = **in
	}
	if in.ServiceRoleARN != nil {
		in, out := &in.ServiceRoleARN, &out.ServiceRoleARN
		*out = new(string)
		**out = **in
	}
	if in.SourceBucketARN != nil {
		in, out := &in.SourceBucketARN, &out.SourceBucketARN
		*out = new(string)
		**out = **in
	}
	if in.StartupScriptS3ObjectVersion != nil {
		in, out := &in.StartupScriptS3ObjectVersion, &out.StartupScriptS3ObjectVersion
		*out = new(string)
		**out = **in
	}
	if in.StartupScriptS3Path != nil {
		in, out := &in.StartupScriptS3Path, &out.StartupScriptS3Path
		*out = new(string)
		**out = **in
	}
	if in.Status != nil {
		in, out := &in.Status, &out.Status
		*out = new(string)
		**out = **in
	}
	if in.Tags != nil {
		in, out := &in.Tags, &out.Tags
		*out = make(map[string]*string, len(*in))
		for key, val := range *in {
			var outVal *string
			if val == nil {
				(*out)[key] = nil
			} else {
				inVal := (*in)[key]
				in, out := &inVal, &outVal
				*out = new(string)
				**out = **in
			}
			(*out)[key] = outVal
		}
	}
	if in.WebserverAccessMode != nil {
		in, out := &in.WebserverAccessMode, &out.WebserverAccessMode
		*out = new(string)
		**out = **in
	}
	if in.WebserverURL != nil {
		in, out := &in.WebserverURL, &out.WebserverURL
		*out = new(string)
		**out = **in
	}
	if in.WebserverVPCEndpointService != nil {
		in, out := &in.WebserverVPCEndpointService, &out.WebserverVPCEndpointService
		*out = new(string)
		**out = **in
	}
	if in.WeeklyMaintenanceWindowStart != nil {
		in, out := &in.WeeklyMaintenanceWindowStart, &out.WeeklyMaintenanceWindowStart
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Environment_SDK.
func (in *Environment_SDK) DeepCopy() *Environment_SDK {
	if in == nil {
		return nil
	}
	out := new(Environment_SDK)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LastUpdate) DeepCopyInto(out *LastUpdate) {
	*out = *in
	if in.CreatedAt != nil {
		in, out := &in.CreatedAt, &out.CreatedAt
		*out = (*in).DeepCopy()
	}
	if in.Error != nil {
		in, out := &in.Error, &out.Error
		*out = new(UpdateError)
		(*in).DeepCopyInto(*out)
	}
	if in.Source != nil {
		in, out := &in.Source, &out.Source
		*out = new(string)
		**out = **in
	}
	if in.Status != nil {
		in, out := &in.Status, &out.Status
		*out = new(string)
		**out = **in
	}
	if in.WorkerReplacementStrategy != nil {
		in, out := &in.WorkerReplacementStrategy, &out.WorkerReplacementStrategy
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LastUpdate.
func (in *LastUpdate) DeepCopy() *LastUpdate {
	if in == nil {
		return nil
	}
	out := new(LastUpdate)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LoggingConfiguration) DeepCopyInto(out *LoggingConfiguration) {
	*out = *in
	if in.DagProcessingLogs != nil {
		in, out := &in.DagProcessingLogs, &out.DagProcessingLogs
		*out = new(ModuleLoggingConfiguration)
		(*in).DeepCopyInto(*out)
	}
	if in.SchedulerLogs != nil {
		in, out := &in.SchedulerLogs, &out.SchedulerLogs
		*out = new(ModuleLoggingConfiguration)
		(*in).DeepCopyInto(*out)
	}
	if in.TaskLogs != nil {
		in, out := &in.TaskLogs, &out.TaskLogs
		*out = new(ModuleLoggingConfiguration)
		(*in).DeepCopyInto(*out)
	}
	if in.WebserverLogs != nil {
		in, out := &in.WebserverLogs, &out.WebserverLogs
		*out = new(ModuleLoggingConfiguration)
		(*in).DeepCopyInto(*out)
	}
	if in.WorkerLogs != nil {
		in, out := &in.WorkerLogs, &out.WorkerLogs
		*out = new(ModuleLoggingConfiguration)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LoggingConfiguration.
func (in *LoggingConfiguration) DeepCopy() *LoggingConfiguration {
	if in == nil {
		return nil
	}
	out := new(LoggingConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LoggingConfigurationInput) DeepCopyInto(out *LoggingConfigurationInput) {
	*out = *in
	if in.DagProcessingLogs != nil {
		in, out := &in.DagProcessingLogs, &out.DagProcessingLogs
		*out = new(ModuleLoggingConfigurationInput)
		(*in).DeepCopyInto(*out)
	}
	if in.SchedulerLogs != nil {
		in, out := &in.SchedulerLogs, &out.SchedulerLogs
		*out = new(ModuleLoggingConfigurationInput)
		(*in).DeepCopyInto(*out)
	}
	if in.TaskLogs != nil {
		in, out := &in.TaskLogs, &out.TaskLogs
		*out = new(ModuleLoggingConfigurationInput)
		(*in).DeepCopyInto(*out)
	}
	if in.WebserverLogs != nil {
		in, out := &in.WebserverLogs, &out.WebserverLogs
		*out = new(ModuleLoggingConfigurationInput)
		(*in).DeepCopyInto(*out)
	}
	if in.WorkerLogs != nil {
		in, out := &in.WorkerLogs, &out.WorkerLogs
		*out = new(ModuleLoggingConfigurationInput)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LoggingConfigurationInput.
func (in *LoggingConfigurationInput) DeepCopy() *LoggingConfigurationInput {
	if in == nil {
		return nil
	}
	out := new(LoggingConfigurationInput)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MetricDatum) DeepCopyInto(out *MetricDatum) {
	*out = *in
	if in.MetricName != nil {
		in, out := &in.MetricName, &out.MetricName
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MetricDatum.
func (in *MetricDatum) DeepCopy() *MetricDatum {
	if in == nil {
		return nil
	}
	out := new(MetricDatum)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModuleLoggingConfiguration) DeepCopyInto(out *ModuleLoggingConfiguration) {
	*out = *in
	if in.CloudWatchLogGroupARN != nil {
		in, out := &in.CloudWatchLogGroupARN, &out.CloudWatchLogGroupARN
		*out = new(string)
		**out = **in
	}
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.LogLevel != nil {
		in, out := &in.LogLevel, &out.LogLevel
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModuleLoggingConfiguration.
func (in *ModuleLoggingConfiguration) DeepCopy() *ModuleLoggingConfiguration {
	if in == nil {
		return nil
	}
	out := new(ModuleLoggingConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModuleLoggingConfigurationInput) DeepCopyInto(out *ModuleLoggingConfigurationInput) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.LogLevel != nil {
		in, out := &in.LogLevel, &out.LogLevel
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModuleLoggingConfigurationInput.
func (in *ModuleLoggingConfigurationInput) DeepCopy() *ModuleLoggingConfigurationInput {
	if in == nil {
		return nil
	}
	out := new(ModuleLoggingConfigurationInput)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetworkConfiguration) DeepCopyInto(out *NetworkConfiguration) {
	*out = *in
	if in.SecurityGroupIDs != nil {
		in, out := &in.SecurityGroupIDs, &out.SecurityGroupIDs
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.SecurityGroupRefs != nil {
		in, out := &in.SecurityGroupRefs, &out.SecurityGroupRefs
		*out = make([]*corev1alpha1.AWSResourceReferenceWrapper, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(corev1alpha1.AWSResourceReferenceWrapper)
				(*in).DeepCopyInto(*out)
			}
		}
	}
	if in.SubnetIDs != nil {
		in, out := &in.SubnetIDs, &out.SubnetIDs
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.SubnetRefs != nil {
		in, out := &in.SubnetRefs, &out.SubnetRefs
		*out = make([]*corev1alpha1.AWSResourceReferenceWrapper, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(corev1alpha1.AWSResourceReferenceWrapper)
				(*in).DeepCopyInto(*out)
			}
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkConfiguration.
func (in *NetworkConfiguration) DeepCopy() *NetworkConfiguration {
	if in == nil {
		return nil
	}
	out := new(NetworkConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StatisticSet) DeepCopyInto(out *StatisticSet) {
	*out = *in
	if in.SampleCount != nil {
		in, out := &in.SampleCount, &out.SampleCount
		*out = new(int64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StatisticSet.
func (in *StatisticSet) DeepCopy() *StatisticSet {
	if in == nil {
		return nil
	}
	out := new(StatisticSet)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UpdateError) DeepCopyInto(out *UpdateError) {
	*out = *in
	if in.ErrorCode != nil {
		in, out := &in.ErrorCode, &out.ErrorCode
		*out = new(string)
		**out = **in
	}
	if in.ErrorMessage != nil {
		in, out := &in.ErrorMessage, &out.ErrorMessage
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UpdateError.
func (in *UpdateError) DeepCopy() *UpdateError {
	if in == nil {
		return nil
	}
	out := new(UpdateError)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UpdateNetworkConfigurationInput) DeepCopyInto(out *UpdateNetworkConfigurationInput) {
	*out = *in
	if in.SecurityGroupIDs != nil {
		in, out := &in.SecurityGroupIDs, &out.SecurityGroupIDs
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UpdateNetworkConfigurationInput.
func (in *UpdateNetworkConfigurationInput) DeepCopy() *UpdateNetworkConfigurationInput {
	if in == nil {
		return nil
	}
	out := new(UpdateNetworkConfigurationInput)
	in.DeepCopyInto(out)
	return out
}
